export enum ProposalRejectionReason {
  USER_BLOCKED = 'USER_BLOCKED',
  REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
  REQUEST_NOT_ACTIVE = 'REQUEST_NOT_ACTIVE',
  OWN_REQUEST = 'OWN_REQUEST',
  ALREADY_PROPOSED = 'ALREADY_PROPOSED',
}
